id = "base64"
name = "Base64"
version = "0.1.0"
schema_version = 1
authors = ["Marcus Cvjeticanin <mjovanc@icloud.com>"]
description = "Base64 multi-format encode and decode for Zed"
repository = "https://github.com/mjovanc/zed-base64"

[slash_commands.encode]
description = "Encode text in a specified format (e.g., base64, url, hex)"
requires_argument = true

[slash_commands.decode]
description = "Decode text from a specified format (e.g., base64, url, hex)"
requires_argument = true
